### ISSUE TITLE
CLJC Port

### ISSUE THREAD

**Issue by colonelrascals** [nrepl/bencode#1] opened 2018-10-30 15:46 UTC
Would a port to CLJC be the best solution for ClojureScript-compatibility?

**Comment by bbatsov** [comment] 2018-10-30 15:57
Yeah, totally. That's the reason we extracted this library in the first place from nREPL - so that it can eventually to ported to cljc and it could be easier to write ClojureScript clients for the default transport.

**Comment by colonelrascals** [comment] 2018-10-30 16:18
This is great! I think I should be able to find some time to work on a port!

**Comment by bbatsov** [comment] 2018-10-30 16:28
That would be much appreciated!

**Comment by SevereOverfl0w** [comment] 2018-10-30 16:37
Just a note, the decoder _should not_ operate on strings. It should operate on a stream of data, e.g. network data coming in chunks.

Too many bugs are caused by half-finished streams of data.

**Comment by colonelrascals** [comment] 2018-11-07 16:05
I'm just going to go ahead an ask the question. 

Could we use messagepack as an alternative?

**Comment by colonelrascals** [comment] 2018-11-07 18:00
to expand:
Is there something about bencode that makes it preferable for nrepl as opposed to using MessagePack or even JSON as a data exchange format?

I suspect the answer is "yes" and it has something to do with "stream of data" like @SevereOverfl0w mentioned, but I am not entirely sure.

Apologies if this is a silly question. Just trying to understand the problem domain better :)

**Comment by bbatsov** [comment] 2018-11-07 18:12
> Is there something about bencode that makes it preferable for nrepl as opposed to using MessagePack or even JSON as a data exchange format?

nREPL is data format-agnostic. You can use whatever data format you want, provided you implement nREPL's transport API for it (see https://nrepl.xyz/nrepl/design/transports.html). The default transport is bencode, because we have to be very careful with the 3rd party deps we use in nREPL, as they might end up conflicting with some of your application's deps. That's also why this bencode library lived in nREPL itself for a very long time. There's also the fact that bencode is a very simple format, so pretty much any client can handle it relatively easy. That's not going to be the case for something like EDN or MessagePack. :-) 

I hope this makes sense.

**Comment by bbatsov** [comment] 2018-11-12 11:44
Btw, once we add the EDN transport https://github.com/nrepl/nrepl/pull/67 this might become a mute topic. I assume ClojureScript clients would naturally prefer using EDN over bencode. //cc @PEZ

**Comment by arichiardi** [comment] 2018-11-13 03:03
FWIW, I had a look and punted on this exactly because of edn support coming up. There are so many things relying on Java primitives that it is almost worth writing a new cljs-only lib or use a JavaScript lib.

**Comment by arichiardi** [comment] 2018-11-13 03:12
I was eyeing this: https://github.com/themasch/node-bencode/blob/master/README.md

It does not look like it works out of streams but it processes buffers. Was thinking that I actually do not really like what the bencode lib does at the moment. It involves both host interop and "logic". Ideally there should be a layer taking care of the stream of data in and a lib just trying to translate the buffers - the latter being a set of very simple .cljc files.

**Comment by PEZ** [comment] 2018-11-16 07:52
I am so ready to say goodbye to Bencode! nrepl/nrepl#67 gives me hope.

**Comment by bbatsov** [comment] 2018-11-16 12:08
OK, I guess we can safely close this then.

**Closed as completed by bbatsov** 2018-11-16 12:08 UTC

**Comment by sergeiudris** [comment] 2021-03-17 06:23
could you suggest/point in the right direction please:
- making an editor extension, runtimes are nodejs/browser
- extension needs to communicate with existing tools - shadow-cljs, lein etc. that run their nrepl servers with bencode transport
- as of now imported https://github.com/themasch/node-bencode, but there are errors and it's unclear whether it is compatible with nrepl's beconde (is it?)

i guess the question:
- which bencode implementation should be used from nodejs runtime to exchange data with nrepl servers that did not choose edn as their transport?

**Comment by bbatsov** [comment] 2021-03-17 07:18
There's nothing nREPL-specific about this particular library. It was just extracted from nREPL so Clojure devs looking for a bencode library can use it. I guess @PEZ and @mauricioszabo can share here what's the bencode library they are using. In general bencode is so simple that I assume many clients just implement bencode internally.

**Comment by mauricioszabo** [comment] 2021-03-17 13:05
@bbatsov, @sergeiudris gladly: https://github.com/mauricioszabo/repl-tooling/blob/master/src/repl_tooling/nrepl/bencode.cljs

If you need help on how to use it, just see the test: https://github.com/mauricioszabo/repl-tooling/blob/master/test/repl_tooling/nrepl/nrepl_test.cljs#L36-L69

The "encoder" is really simple: you send an EDN, it returns a bencode string. The "decoder" is a little bit harder, because it handles incomplete output - so, if you receive a stream of data, and that stream is not a full map or array, for example, it'll parse until it can, then "cache" the result and keep parsing when there's more info. There are performance tests commented on the code too, if you want to check :+1:
